## Guardar y levantar datos - Laboratorio 3

En esta notebook tenemos instrucciones estándar para el guardado de datos.

**Guardar una única adquisición**

Hago un ejemplo sintético, tienen que adaptarlo a los nombres de las variables que hayan elegido.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

#creo valores ficticios 
freq = 5
tiempo = np.linspace(0, 1, 1000)    
voltaje_1 = np.sin(tiempo*2*np.pi*freq)
voltaje_2 = (1/freq) * np.sin(tiempo*2*np.pi*freq)

############################## A partir de aca ###########################

#los acomodamos en un dataframe de pandas
df = pd.DataFrame({'Time':tiempo,'V1':voltaje_1,'V2':voltaje_2})

#si queremos guardar la frecuencia (se agrega una columna extra)
df["Frequency"] = freq

#Aca podemos decir que la frecuencia y el tiempo sean indices
df.set_index(["Frequency", "Time"])

                              V1            V2
Frequency Time
5         0.000000  0.000000e+00  0.000000e+00
          0.001001  3.144219e-02  6.288438e-03
          0.002002  6.285329e-02  1.257066e-02
          0.003003  9.420224e-02  1.884045e-02
          0.004004  1.254580e-01  2.509161e-02
...                          ...           ...
          0.995996 -1.254580e-01 -2.509161e-02
          0.996997 -9.420224e-02 -1.884045e-02
          0.997998 -6.285329e-02 -1.257066e-02
          0.998999 -3.144219e-02 -6.288438e-03
          1.000000 -1.224647e-15 -2.449294e-16

[1000 rows x 2 columns]

In [ ]:
#Ahora lo guardamos
save_folder = 'path/'
df.to_csv(save_folder+"data_test.csv", index=False, header=True)

**Levantar los datos y graficar**

In [ ]:
df_ff = pd.read_csv(save_folder+"data_test.csv", index_col=["Frequency", "Time"])

df_ff

In [ ]:
#Graficar 
tiempo = df["Time"].values
v1 = df["V1"].values

plt.figure(figsize=(4,1))
plt.plot(tiempo, v1)
plt.show()

## Guardado de datos de un loop 

Si hacemos un barrido en frecuencia y queremos guardar los datos en un unico archivo.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

# Example data
frequencies = [100, 200, 300]
N = 1000  # Number of time points per frequency

# Create empty lists to store all data
all_frequencies = []
all_times = []
all_voltage1 = []
all_voltage2 = []

for f in frequencies:
    time = np.linspace(0, 1, N) 
    voltage1 = np.sin(2 * np.pi * f * time)  
    voltage2 = np.cos(2 * np.pi * f * time)  
    
    all_frequencies.extend([f] * len(time))
    all_times.extend(time)
    all_voltage1.extend(voltage1)
    all_voltage2.extend(voltage2)

# Create DataFrame in one step
df = pd.DataFrame({
    "Frequency": all_frequencies,
    "Time": all_times,
    "Voltage1": all_voltage1,
    "Voltage2": all_voltage2
})

df

      Frequency      Time      Voltage1  Voltage2
0           100  0.000000  0.000000e+00  1.000000
1           100  0.001001  5.882940e-01  0.808647
2           100  0.002002  9.514445e-01  0.307820
3           100  0.003003  9.504718e-01 -0.310811
4           100  0.004004  5.857481e-01 -0.810493
...         ...       ...           ...       ...
2995        300  0.995996 -9.533617e-01  0.301830
2996        300  0.996997  5.831964e-01  0.812331
2997        300  0.997998  5.908340e-01 -0.806793
2998        300  0.998999 -9.504718e-01 -0.310811
2999        300  1.000000 -1.019005e-13  1.000000

[3000 rows x 4 columns]

In [ ]:
#Guardado
save_folder = 'path/'
df.to_csv(save_folder+"data_test.csv", index=False, header=True)

In [ ]:
#Levantar los datos
df_ff = pd.read_csv(save_folder+"data_test.csv", index_col=["Frequency", "Time"])

df_ff

**Acceder a los datos de una frecuencia particular**

In [ ]:
#Forma 1

df_100 = df_ff.loc[100]

df_100.head()

In [ ]:
#Forma 2
df_200Hz = df[df["Frequency"] == 200]

df_200Hz